### PR TITLE
Add option to run without downloading/installing a pack

### PR DESCRIPTION
**Pull request by Darkere**
depending on modpackformat it will just run (zip) or download the mods from the manifest (curse)

edit: not tested. will do so soon ™️

### CODE REVIEW

**Comment by Darkere** [comment]
works now :)

**Comment by Darkere** [comment]
[zippedcausegithub.zip](https://github.com/EnigmaticaModpacks/ServerStarter/files/8357937/zippedcausegithub.zip)

compiled version in case that's needed

**Review by NielsPilgaard — APPROVED** [review]

**Comment by NielsPilgaard** [comment]
Awesome thanks!

**Comment by NielsPilgaard** [comment]
So I can replace the bat/sh server start scripts in the automation folder of our packs with this, right? 😄

**Comment by Darkere** [comment]
Yes. Though the installPack config option needs to be set to false for that.

**Pull request merged**
